//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.15 at 08:13:51 PM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/aufgabe3d", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package aufgabe4;
